import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { TanstackQueryProvider } from '@/components/providers/tanstack-query-provider'
import { Toaster } from '@/components/shared/sonner'

import { cn } from '@/lib/utils'

import '@/assets/styles/tailwind.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	robots: {
		index: false,
		follow: false
	}
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen font-sans antialiased',
					GeistSans.className
				)}
			>
				<TanstackQueryProvider>
					{children}
					<Toaster
						toastOptions={{
							classNames: {
								error: 'bg-red-100 text-red-800',
								success: 'bg-emerald-100 text-emerald-800',
								warning: 'bg-yellow-100 text-yellow-800',
								info: 'bg-sky-100 text-sky-800'
							}
						}}
					/>
				</TanstackQueryProvider>
			</body>
		</html>
	)
}
